import { calculateFoodScore } from './scoringEngine.js';


/**
 * Convert a serving-size string into grams when a gram amount
 * is explicitly present.
 *
 * Examples:
 * "40 g" -> 40
 * "40g (2 biscuits)" -> 40
 * "1 serving (40 g)" -> 40
 *
 * We only use an explicitly printed gram value.
 * We never guess the serving weight.
 */
function extractServingGrams(servingSize) {
  if (!servingSize) return null;

  const match = String(servingSize).match(
    /(\d+(?:\.\d+)?)\s*g\b/i
  );

  if (!match) return null;

  const grams = Number(match[1]);

  return Number.isFinite(grams) && grams > 0
    ? grams
    : null;
}


/**
 * Convert nutrition values from their printed basis into
 * both per-serving and per-100g values.
 *
 * Labelicious performs these calculations locally so the AI
 * never needs to invent or calculate nutrition values.
 */
function normalizeNutrition(
  nutrition = {},
  servingSize
) {
  const basis = nutrition.basis || 'unknown';

  const servingGrams =
    extractServingGrams(servingSize);

  const nutrientKeys = [
    'calories',
    'protein',
    'carbohydrates',
    'totalFat',
    'saturatedFat',
    'fiber',
    'totalSugar',
    'addedSugar',
    'sodium'
  ];

  const perServing = {};
  const per100g = {};

  for (const key of nutrientKeys) {
    const rawValue = nutrition[key];

    if (rawValue == null) {
      perServing[key] = null;
      per100g[key] = null;
      continue;
    }

    const value = Number(rawValue);

    if (!Number.isFinite(value)) {
      perServing[key] = null;
      per100g[key] = null;
      continue;
    }

    // ----------------------------------------------------------
    // Nutrition was explicitly printed per serving
    // ----------------------------------------------------------

    if (basis === 'perServing') {
      perServing[key] = value;

      if (servingGrams != null) {
        per100g[key] =
          Number(
            ((value / servingGrams) * 100).toFixed(2)
          );
      } else {
        per100g[key] = null;
      }

      continue;
    }

    // ----------------------------------------------------------
    // Nutrition was explicitly printed per 100g
    // ----------------------------------------------------------

    if (basis === 'per100g') {
      per100g[key] = value;

      if (servingGrams != null) {
        perServing[key] =
          Number(
            ((value * servingGrams) / 100).toFixed(2)
          );
      } else {
        perServing[key] = null;
      }

      continue;
    }

    // ----------------------------------------------------------
    // Unknown basis
    // ----------------------------------------------------------
    //
    // Preserve the extracted number only as raw data.
    // Do not pretend that it is per-serving or per-100g.
    //

    perServing[key] = null;
    per100g[key] = null;
  }

  return {
    basis,
    servingGrams,
    perServing,
    per100g
  };
}


/**
 * Convert a scoring-engine insight into the status used
 * by the existing frontend cards.
 */
function getMetricStatus(insight) {
  if (!insight) {
    return 'neutral';
  }

  if (insight.level === 'positive') {
    return 'positive';
  }

  if (insight.level === 'attention') {
    return 'negative';
  }

  return 'neutral';
}


/**
 * Get the user-facing interpretation generated by
 * scoringEngine.js.
 *
 * This prevents AnalysisPage from inventing its own
 * nutrition labels.
 */
function getMetricStatusLabel(insight) {
  if (!insight || !insight.label) {
    return 'Not available';
  }

  return insight.label;
}


/**
 * Transforms validated AI extraction data into the
 * unified Labelicious product schema.
 */
export function transformAiDataToProduct(
  aiData,
  activeProfile = { id: 'general' }
) {
  const {
    product,
    nutrition,
    ingredients,
    analysis,
    ingredientSummary
  } = aiData;

  const normalizedNutrition =
    normalizeNutrition(
      nutrition,
      product.servingSize
    );

  /**
   * Labelicious scoring uses per-serving nutrition when
   * available because that is what the user actually consumes.
   *
   * If the serving basis cannot be established, fall back
   * to the extracted values without changing the extracted
   * numbers themselves.
   */
  const scoringNutrition =
    normalizedNutrition.perServing.calories != null ||
    normalizedNutrition.perServing.protein != null ||
    normalizedNutrition.perServing.addedSugar != null ||
    normalizedNutrition.perServing.sodium != null
      ? normalizedNutrition.perServing
      : nutrition;

  const scoreResult =
    calculateFoodScore(
      scoringNutrition,
      ingredients,
      activeProfile
    );

  const servingNutrition =
    normalizedNutrition.perServing;

  const nutritionInsights =
    scoreResult.nutritionInsights || {};

  // ----------------------------------------------------------
  // Key nutrition metrics
  // ----------------------------------------------------------
  //
  // These cards now use the same interpretation produced by
  // scoringEngine.js instead of hard-coded "positive",
  // "neutral", or "reference context" labels.
  // ----------------------------------------------------------

  const fiberVal =
    servingNutrition.fiber;

  const proteinVal =
    servingNutrition.protein;

  const addedSugarVal =
    servingNutrition.addedSugar;

  const sodiumVal =
    servingNutrition.sodium;

  const keyMetrics = [
    {
      label: 'Fiber',

      value:
        fiberVal == null
          ? 'Not available'
          : `${fiberVal}g`,

      status:
        getMetricStatus(
          nutritionInsights.fiber
        ),

      statusLabel:
        getMetricStatusLabel(
          nutritionInsights.fiber
        )
    },

    {
      label: 'Protein',

      value:
        proteinVal == null
          ? 'Not available'
          : `${proteinVal}g`,

      status:
        getMetricStatus(
          nutritionInsights.protein
        ),

      statusLabel:
        getMetricStatusLabel(
          nutritionInsights.protein
        )
    },

    {
      label: 'Added Sugar',

      value:
        addedSugarVal == null
          ? 'Not available'
          : `${addedSugarVal}g`,

      status:
        getMetricStatus(
          nutritionInsights.addedSugar
        ),

      statusLabel:
        getMetricStatusLabel(
          nutritionInsights.addedSugar
        )
    },

    {
      label: 'Sodium',

      value:
        sodiumVal == null
          ? 'Not available'
          : `${sodiumVal}mg`,

      status:
        getMetricStatus(
          nutritionInsights.sodium
        ),

      statusLabel:
        getMetricStatusLabel(
          nutritionInsights.sodium
        )
    }
  ];


  // ----------------------------------------------------------
  // Highlights
  // ----------------------------------------------------------

  const highlights =
    analysis.positives?.length > 0
      ? analysis.positives
      : [
          fiberVal != null && fiberVal >= 3
            ? `Contains ${fiberVal}g dietary fiber per serving`
            : null,

          proteinVal != null && proteinVal >= 5
            ? `Provides ${proteinVal}g protein per serving`
            : null
        ].filter(Boolean);

  if (highlights.length === 0) {
    highlights.push(
      'Nutrition and ingredient facts successfully extracted from label'
    );
  }


  // ----------------------------------------------------------
  // Concerns
  // ----------------------------------------------------------

  const concerns =
    analysis.concerns?.length > 0
      ? analysis.concerns
      : [
          addedSugarVal != null && addedSugarVal > 10
            ? `Contains ${addedSugarVal}g added sugar per serving`
            : null,

          servingNutrition.saturatedFat != null &&
          servingNutrition.saturatedFat > 3
            ? `Contains ${servingNutrition.saturatedFat}g saturated fat per serving`
            : null,

          sodiumVal != null && sodiumVal > 300
            ? `Contains ${sodiumVal}mg sodium per serving`
            : null,

          ingredientSummary.additivesCount > 2
            ? `Contains ${ingredientSummary.additivesCount} identified functional additives`
            : null
        ].filter(Boolean);


  // ----------------------------------------------------------
  // Things to Understand
  // ----------------------------------------------------------
  //
  // Previously this fallback ALWAYS created three attention
  // points, which meant the UI could never honestly show zero.
  //
  // Now we only create a point when there is something
  // meaningful to review.
  // ----------------------------------------------------------

  let attentionPoints = [];

  if (analysis.attentionPoints?.length > 0) {
    attentionPoints = analysis.attentionPoints;
  } else {
    if (
      ingredientSummary.additivesCount > 0
    ) {
      attentionPoints.push(
        `${ingredientSummary.additivesCount} functional additive${
          ingredientSummary.additivesCount === 1
            ? ''
            : 's'
        } identified in the ingredient list.`
      );
    }

    if (
      addedSugarVal != null &&
      addedSugarVal > 10
    ) {
      attentionPoints.push(
        `Added sugar contributes ${addedSugarVal}g per serving.`
      );
    }

    if (
      sodiumVal != null &&
      sodiumVal >= 400
    ) {
      attentionPoints.push(
        `Sodium contributes ${sodiumVal}mg per serving.`
      );
    }

    if (
      servingNutrition.saturatedFat != null &&
      servingNutrition.saturatedFat >= 4
    ) {
      attentionPoints.push(
        `Saturated fat contributes ${servingNutrition.saturatedFat}g per serving.`
      );
    }

    if (
      ingredients.some(
        ingredient =>
          ingredient.category === 'Allergen' ||
          ingredient.isAllergen === true
      )
    ) {
      attentionPoints.push(
        'Review the ingredient list for personal allergen sensitivities.'
      );
    }
  }


  // ----------------------------------------------------------
  // Summary
  // ----------------------------------------------------------

  const summary =
    analysis.verdict &&
    analysis.verdict !== scoreResult.verdict
      ? analysis.verdict
      : 'Based on the extracted nutrition and ingredient information.';


  // ----------------------------------------------------------
  // Final Labelicious product
  // ----------------------------------------------------------

  return {
    id:
      `ai-scan-${Date.now()}`,

    name:
      product.name ||
      'Analyzed Food Label',

    brand:
      product.brand ||
      'Brand Detected',

    category:
      product.category ||
      'Packaged Grocery',

    scannedAt:
      'Just now (Real AI)',

    // --------------------------------------------------------
    // Score
    // --------------------------------------------------------

    score:
      scoreResult.score,

    scoreLabel:
      scoreResult.scoreLabel,

    scoreColor:
      scoreResult.scoreColor,

    verdict:
      scoreResult.verdict,

    summary,

    // --------------------------------------------------------
    // Serving information
    // --------------------------------------------------------

    servingSize:
      product.servingSize ||
      '1 serving',

    nutritionBasis:
      normalizedNutrition.basis,

    servingGrams:
      normalizedNutrition.servingGrams,

    // --------------------------------------------------------
    // Normalized nutrition
    // --------------------------------------------------------

    nutritionPerServing:
      normalizedNutrition.perServing,

    nutritionPer100g:
      normalizedNutrition.per100g,

    // --------------------------------------------------------
    // Nutrition insights
    // --------------------------------------------------------
    //
    // Preserve these so the frontend can use the same
    // interpretation everywhere.
    // --------------------------------------------------------

    nutritionInsights,

    // --------------------------------------------------------
    // Existing frontend compatibility
    // --------------------------------------------------------

    calories:
      servingNutrition.calories,

    nutritionTable: {
      calories:
        servingNutrition.calories,

      protein:
        servingNutrition.protein,

      carbs:
        servingNutrition.carbohydrates,

      addedSugar:
        servingNutrition.addedSugar ??
        servingNutrition.totalSugar,

      totalFat:
        servingNutrition.totalFat,

      saturatedFat:
        servingNutrition.saturatedFat,

      sodium:
        servingNutrition.sodium,

      fiber:
        servingNutrition.fiber
    },

    // --------------------------------------------------------
    // Key metrics
    // --------------------------------------------------------

    keyMetrics,

    // --------------------------------------------------------
    // Analysis
    // --------------------------------------------------------

    highlights,

    concerns,

    ingredientSummary,

    ingredients,

    attentionPoints,

    // --------------------------------------------------------
    // Raw extracted nutrition
    // --------------------------------------------------------
    //
    // Kept for transparency and comparison fallback.
    // These values retain their original printed basis.
    // --------------------------------------------------------

    extractedNutrition:
      nutrition,

    isRealAi:
      true
  };
}